tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "gh"
brew "git"
brew "sqlite"
brew "imagemagick"
brew "jq"
brew "openssl@3"
brew "postgresql", restart_service: true
brew "rbenv"
brew "wget"
cask "dbeaver-community"
